version: '3.1'
services:
    mongo:
        image: dbeaver/cloudbeaver:latest
        container_name: cloudbeaver
        ports:
            - 8080:8978
        volumes:
            - ../dockerdata/cloudbeaver:/opt/cloudbeaver/workspace