version: '3.1'
services:
    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        container_name: monogusik
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=project
        volumes:
            - ../dockerdata/mongodb:/data/db
        restart: always
    mongo-client:
        image: mongoclient/mongoclient:latest
        ports:
            - 3000:3000
        container_name: monogusik-client
        restart: always
